### ISSUE TITLE
问卷管理模块 ： 几个可以微调的地方

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#103]

**Comment by JackyReal** [comment]
1. 应用表单 字段可以去掉？
2. “删除问题” 按钮，实际上是删除所有问题，  是不是改成 “删除所有问题” 更清楚一点？
3. 另外删除操作给个提示是不是好一些，让用户对自己的危险操作做确认

**Comment by microlcl** [comment]
Jacky，
“应用表单”应该不能去掉，比如针对business id为婚庆的，应用于回访单和应用管理里面的调查问卷，应该是不同的，这个不同就是用“应用表单”来进行区分的。
如果后续要加上“调查问卷”的功能，可以增加一个表单类别“调查表单”，同时增加一个business id为“调查”即可。
不知我理解的对否。

**Comment by microlcl** [comment]
剩下的两问题2）3）assign给ShiShuai

**Comment by lss0720** [comment]
2) 3)已经实现并且code已经提交。
