### ISSUE TITLE
调查问卷（问卷管理） 模块 ： 按钮问题

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#104]
1.  “发布问卷” 按钮样式和其他几个（比如查看，修改等 都是小图标加一个文字连接）明显不一样
2. “废弃” 按钮点击后，弹出的提示框和其他地方的提示框不一样
3.  问卷 “废弃” 后， “废弃” 按钮依然可见， 但是“发布” 后 “发布” 按钮就消失了，我们可以做做个类似的控制吧
4. “废弃” 的问卷可以修改，然后再被“发布” 使用的，目前不可以被“发布”

**Comment by 118yangbin** [comment]
1.发布问卷按钮改成跟其他的一样了。
2.这个弹出框，删除的时候，都是这样提示的，要改成跟哪个一样？
3.已经改成废弃之后，废弃按钮就消失了。

**Comment by 118yangbin** [comment]
4.“废弃” 的问卷可以修改，然后再被“发布” 使用的,我这里可以“发布”

**Comment by 118yangbin** [comment]
2.我把废弃修改为跟发布一样，不提示，直接废弃。
4.已经把废弃的问卷，可以直接发布，之前是需要先修改提交之后再发布。

**Comment by JackyReal** [comment]
整体效果很不错，就有一个小疑问：

看到有一些记录 “废弃” 按钮和 “发布” 按钮， 同时存在，正常的话，按照目前修改的方式，这两个按钮只能存在一个对吧

是有一个小bug 吗？

**Comment by 118yangbin** [comment]
目前问卷是草稿的时候，既可以废弃，也可以发布。我回头跟ShiShuai确认一下。这里应该是有个中间状态草稿。

**Comment by 118yangbin** [comment]
废弃后，是废弃状态，从废弃状态提交，就变成了草稿状态，草稿状态发布，就是发布状态.
所以草稿状态的时候，是可以同时有“废弃”和“发布”按钮的。
