### ISSUE TITLE
协同作业模块 ： 拥有者下拉列表为空

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#105]
拥有者下拉列表为空

**Comment by microlcl** [comment]
这个是新增的时候，默认拥有着下拉列表为空，但是如果选择“所属部门”后，这个下拉列表是联动的。
如果需要在没有选择所属部门的前提下，依然让拥有者下拉列表有数据，解决办法如下：
当新增task的时候，“所属部门”默认为“创建者”所属的部门，顺便激活“拥有者”的下拉菜单联动功能

**Comment by microlcl** [comment]
这个defect对功能性影响很小，优先级应该靠后。 :)

**Comment by JackyReal** [comment]
明白了，可以给个提示也行，如果没有先选择部门，给个提示先选择“部门”？ 这个effort 是不是小一点？

**Comment by JackyReal** [comment]
二级联动，一般都是提示一下即可了，我们加个校验提示吧， 怎么样？

**Comment by 118yangbin** [comment]
在选择的时候，给了默认的值该id所在部门下的所有人员。
