### ISSUE TITLE
协同作业模块 ： 修改页面几个问题

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#106]
1.  “计划完成时间”  字段需要必录校验， 目前的情况是，用户可以不录入，结果保存的时候 500 错误
2. “任务类型”， “优先级”  下拉不能让用户选择根节点， 这样保存的结果无意义
3. “添加评论”  不需要权限控制，可以放开， 在配置的时候可以不加这个
4. “附属内容” tab 页面，应该也加一个“保存” 按钮？  目前是上传的文件自动保存了，但是 订阅没有做保存；
   或者直接保存，就不要另外一个保存按钮？
5.  优先级  是否可以对应不同的 图片识别一下， 类似我们目前的RTC，这样更清晰友好一些， 这个优先级低一些

**Comment by 118yangbin** [comment]
1.已经修改好。

**Comment by 118yangbin** [comment]
4.已经增加保存按钮。

**Comment by microlcl** [comment]
3也fix了
关于2）， 建议参考“需求管理”里面的左上角的“状态”下拉列表，是用combobox做的，这里不应该用combotree

**Comment by 118yangbin** [comment]
2.已经改好。

**Comment by 118yangbin** [comment]
5.在list页面已经改好了，但是在修改和添加那里，是下拉的，看起来不太好改。
