### ISSUE TITLE
搜索栏：屏幕缩小后，搜索栏布局乱了

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#109]
采用bootstrap的响应式布局修改搜索栏：
行内表单：
http://v2.bootcss.com/base-css.html#forms

**Comment by lss0720** [comment]
这块儿、我尝试了很久、没有改好。响应式布局不太好弄。

**Comment by lss0720** [comment]
响应式布局、我本地还是没怎么弄好。需要花更多时间研究下。

**Comment by microlcl** [comment]
修改了一下布局，fix了这个问题。
