### ISSUE TITLE
新用户注册

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#111]
登录名  没有做唯一性校验，当我注册了第二个相同的登陆名称的 用户时候，前台500 错误

http://localhost:8080/myprogram/account/register

后台错误消息显示违反唯一性约束

**Comment by microlcl** [comment]
DeQuan,
唯一性校验一直都有，我刚才测试也是好的。你能否double check一下？如果是好的，就close吧

**Comment by DevinYDQ** [comment]
这个校验一开始的时候就做了，我刚刚测试了，我这边也是好用的
