### ISSUE TITLE
需求管理模块 --> 增加联系人

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#114]
应该对应有一个删除功能？
目前我只可以添加，没有地方可以删除，甚至在我提交之前，我应该可以有机会撤销这个添加等

**Comment by microlcl** [comment]
ShiShuai，
上个月你不是做了这个功能吗？选择case后，联系人都会显示出来，我怎么没看到这个功能了？

**Comment by lss0720** [comment]
春雷、这个是可以显示出来联系人的、可能是看的第一条数据没有联系人？
Jacky，我在每个新添加联系人下面增加了个“删除此新加联系人”，已经实现并且提交。

**Comment by microlcl** [comment]
Sorry ShiShuai，
我上面的comment貌似写错地方了，应该是写到你的那个非初次到访的defect里面的. :)
我刚才看了你修改的这个“删除此新加联系人”， 其实是撤销增加的操作。这个可以有！
我觉得你应该在每个联系人下面，都增加这个“删除”button",这样，已经存到数据库的联系人，也能删除了

**Comment by lss0720** [comment]
每个联系人下面，都增加这个“删除”button",这样，而且已经存到数据库的联系人，也实现了数据库删除。

**Comment by JackyReal** [comment]
验证完毕
