### ISSUE TITLE
需求管理模块 ： 校验提示

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#115]
1. 详细tab 页面 ： 有一些必录项，没有填写时，也没有明显的提示，比如 “举行时间”
2. 回访记录 --》 增加回访记录
   
   回访细节section，  客户姓名  是必须有值的，这个校验做了，但是提示不明显，我们可否把必录入校验做的全部一致，除了对应表单元素，红色提示之外，我们页面上方打印出来消息，这样比较清楚一些； 比如这个地方如果回访细节 section 折叠着，一直不能提交，但是不知道是什么原因

按照正常流程，从前面模块流过来的数据是做了这些校验的，会保证这些数据不为空，但是这个模块也提供了新增入口，同时用户有修改的可能性，所以再次校验这些必录项目是有必要的

**Comment by JackyReal** [comment]
这个问题没有解决

2 回访记录 --》 增加回访记录

回访细节section， 客户姓名 是必须有值的，这个校验做了，但是提示不明显，我们可否把必录入校验做的全部一致，除了对应表单元素，红色提示之外，我们页面上方打印出来消息，这样比较清楚一些； 比如这个地方如果回访细节 section 折叠着，一直不能提交，但是不知道是什么原因

**Comment by DevinYDQ** [comment]
三个浏览器里测试都有校验提示
