### ISSUE TITLE
需求管理模块 --》 增加到访记录

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#116]
1.  缺少  到访问卷功能， 需要做成和回访类似
2. 提交后，目前跳转到进店管理模块？  请跳转到需求查询列表， 和 增加到访记录一样。
   但是这里貌似是直接复用了进店那里的页面？ 需要仔细看一下，以防改完这里影响了进店管理的功能。

**Comment by microlcl** [comment]
Jacky，
1)到访也需要问卷吗？我记得当时商量的是，前台不会问很多问题，所以不需要问卷。
2) 需求管理里面关于“到访”“回访”的单据，都是跳转到“进店管理”的里面相应的页面的。

**Comment by lss0720** [comment]
Jacky，这个是否需要再商量一下？

**Comment by JackyReal** [comment]
不是的，这个地方是两个概念 ：
前台是用进店管理模块，不需要cover 需求。  这个地方设计到的是“到访记录” 涉及到需求变化，所以是需要问卷的。

**Comment by JackyReal** [comment]
和到访记录添加设计的一样就可以了

**Comment by lss0720** [comment]
1> 初次到访页面增加了调查问卷、而且已经解决了visitService写库不成功的问题。
2> 接下来实现非初次到访页面的调查问卷。
3> 最后需要修改查看页面增加调查问卷。

**Comment by JackyReal** [comment]
1> 初次到访页面增加了调查问卷、而且已经解决了visitService写库不成功的问题。

前台用的 “进店管理” 模块的  初次到访功能， 不需要问卷， 因为他们不cover 需求；  只有需求管理模块的， 增加”到访记录“ 才有问卷功能

**Comment by lss0720** [comment]
Roll back了初次到访的修改、应该到需求管理里面增加到访记录的调查问卷。

**Comment by lss0720** [comment]
1> 2> 3> 全部已经实现。

**Comment by JackyReal** [comment]
验证完毕，但是发现了新问题，开了新的issue
