### ISSUE TITLE
进店管理 ---》  非初次到访

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#117]
在增加到访人的时候，我们是否可以从已经有的列表里面选取，或者有一个联系人选择器？
1. 减少用户输入量
2. 防止系统重复录入相同的联系人  （我们代码应该是没有做校验，而且不是很容易做校验的）

这里的方法可以复用到， 增加回访记录，填写回访人的时候。
我记得是有一个修改，之前提到过，是一直没有提交吗？

**Comment by lss0720** [comment]
这个、已经实现了、只是可能某些案例没有数据。你可以选择“张三的婚礼”来看效果。
