### ISSUE TITLE
需求管理模块 ： 权限问题

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#118]
新建用户，分配这个模块的所有权限， 然后使用

1) 增加到访记录功能， 401 错误

http://localhost:8080/myprogram/visit/update/9

2). 查看，修改，保存回访记录也都 401 错误

这些地方是复用了进店模块的吧， 我们在这个地方重复配置一下，但是 名字是 “增加到访记录” 等？ 是否可行。  不过感觉复用总会给权限带来一些隐含的问题

**Comment by microlcl** [comment]
Fixed:
1修改了到到访单的跳转逻辑，本页刷新，不跳转到到访list页面，这样解决了从需求表单进入的issue
2. 增加了需求模块到访，和回访的权限配置
