### ISSUE TITLE
方案管理模块 ： 权限问题

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#121]
1. 没有赋给 用户“删除” 权限，但是用户依然有
2. 下载权限 赋给用户， 但是用户依然不可以下载， 也许这个地方可以不控制，默认为用户可以修改方案就可以下载？
3. 导出 方案 没有配置权限，这个地方导出是什么效果我给忘记了 -：）

**Comment by microlcl** [comment]
方案由于上次有异常，我没有完全配置好权限，所以有问题。

**Comment by microlcl** [comment]
1. 删除权限在UI上配置好了。
2. 去掉了下载权限，把下载权限合并到修改权限里面了
3. 导出方案是DeQuan做的导出成xls格式的文件的那个功能，目前可以到处，但是数据不完整。导出权限也合并在修改权限里面了。

如果导出方案也要配置权限，这个就涉及到权限粒度的问题了。这个和下载功能类似，所以就合并到修改权限了。
