### ISSUE TITLE
方案管理模块 ： 音频下载

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#127]
1. 下载历史貌似没有保存上
2. 下载内容是空的， 但是图片是可以的

另外我们下载完毕是否可以更新一下下载历史？ 现在只有重新刷新整个页面才可以看到变化的

**Comment by 118yangbin** [comment]
1.已经解决。

**Comment by 118yangbin** [comment]
2.已经解决。
解决另外一个问题，下载历史记录需要刷新才能看到。
