### ISSUE TITLE
类别管理 ： 系统参数

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#129]
系统参数，至少根节点不能删除，目前是可以自由删除掉的

**Comment by microlcl** [comment]
fixed。
目前有两层控制：
1. 权限，category的删除权限可以配置
2. 即使该人有删除的权限，对于系统参数，当删除的时候，给出了提示“系统参数，不能删除”

**Comment by JackyReal** [comment]
好的。
只有一个问题，是不是我们仅仅限制文件夹不能删除就可以了？目前限制到叶子节点有点太严格了
