### ISSUE TITLE
查询按钮 ： 人员管理和角色管理模块

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#131]
查询按钮和其他模块不一样，而且是英文'search"

**Comment by JackyReal** [comment]
还有另外一个同样的修改 ：

需求管理模块， “新建” 按钮风格和其他模块不太一致，改成一样的吧

**Comment by JackyReal** [comment]
另外一个优化 -：）

角色管理模块， 创建新角色  ---》  新建角色，改为绿色按钮， 一致一下吧

**Comment by JackyReal** [comment]
最后一个地方 ， 场地管理模块， 创建新场地 --》  新建场地   （更名）

**Comment by lss0720** [comment]
人员管理、角色管理、需求管理、场地管理全部做了一致性调整。已经提交code。

**Comment by JackyReal** [comment]
看起来不错-：）
只有一个遗留下的问题 ： 角色管理模块  查询按钮还是英文'search"，而且风格和其他地方不一样

**Comment by lss0720** [comment]
可能我忘了提交了、呵呵、待会我提交下、我本地是改好了的。

**Comment by lss0720** [comment]
已提交。

**Comment by JackyReal** [comment]
验证完毕
