### ISSUE TITLE
产品选择器不能按照类别过滤

### ISSUE THREAD

**Issue by DevinYDQ** [microlcl/scheme_repo#132]
只能选择一个类别，选择多个类别过滤查询结果有问题

**Comment by DevinYDQ** [comment]
search_categoryId : $('#categorySelectorProduct').combotree('getValues')  改为“getValues” 后可以得到所选择的所有分类。
但是发现个新问题， 比如单独选择40，可以得到三个产品。再选一个42，却只包含一个40的产品。

**Comment by microlcl** [comment]
这个不是问题，这两个条件有重叠的结果集，因为一个product可以对应多个category。
你可以double check一下

**Comment by JackyReal** [comment]
DQ, 再次测试一下
