### ISSUE TITLE
案例选择器不好用

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#133]
可以在进店管理模块 ---》 非初次到访模块重现

**Comment by JackyReal** [comment]
这个问题不是每次都有，我记得是

#134  问题之后才可以重现， 我再仔细测试几次，记录一下重现的步骤

**Comment by 118yangbin** [comment]
500那个错误已经解决了，那个问题是因为，保存之后，跳转到刚刚保存的非初次到访，没有带id，id为空，我增加了id。

**Comment by JackyReal** [comment]
案例选择器还是不好用，没有任何数据可以查询的到
