### ISSUE TITLE
需求管理模块 ： 到访记录

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#138]
1. 需要提供和 “回访”一样的效果 ， 可以“查看”  和 “修改” （虽然增加，本质上也是修改）， 只是为了在用户的角度更清晰一些
2. 选择调查问卷的pop up 窗口，类别也应该灰色，并且有一个默认的值， 和“回访记录”效果一样
3. 问卷答完后，提交，，貌似没有保存上？  因为我再次到修改页面（选择到访流水，然后“增加到访记录”）的时候，问卷和答案并没有被铺在页面上

**Comment by microlcl** [comment]
还有两个问题：
1： 三个section（访问细节，案例资料，到访客户信息），默认都是折叠的。应该可以弄成都是展开状态，类似RTC里面。
2： “案例资料”里面的内容应该是只读的，尤其是“案例名称，案例类别”，如果这个能编辑，就乱套了。（可以参考回访记录，回访里面的案例资料是只读的）

**Comment by lss0720** [comment]
Jacky的三个问题还有春雷的两个问题、都已经改完。
