### ISSUE TITLE
资源上传：上传资源文件，如果文件名包含中文，不能显示

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#149]
在server上测试是这样的，主要原因是中文变成了？
DBBFC9B82861FB6CFE01E2BEB37A4AC0_????.jpg

请现在本地重现一下，看看怎么fix。
Thanks

**Comment by 118yangbin** [comment]
有2个问题，
1.保存时用的large路径，显示路径是small，我把显示的改成了large.
2.文件名为中文的问题，需求修改tomcat server.xml文件
<Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" useBodyEncodingForURI="true"  URIEncoding="UTF-8"/>
这个地方增加了useBodyEncodingForURI="true"  URIEncoding="UTF-8"这2个属性。
我本地修改后，要删掉配置的server，重新new server才能生效。这个需要shishuai在server上面配置测试一下。

**Comment by microlcl** [comment]
YangBin,
路径不用修改。否则会run不起来的。如果上传的文件名是英文，一点问题也没有的。所以不要改路径。
