### ISSUE TITLE
资源管理： 不支持模糊 查询

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#150]
在查询界面的"输入关键字"搜索input filed里面，输入关键字。不能查询出结果。
应该是sql没有写成类似： like %keyword% 的形式

**Comment by 118yangbin** [comment]
资源管理--》input -->查询。我本地可以模糊查询。

**Comment by microlcl** [comment]
YangBin，
你本地测试是用的mysql数据库吗？
我们要确保这个模糊查询的功能在mysql环境下也是可以用的。
