### ISSUE TITLE
美化搜索区域：针对资源管理界面，搜索部分分成两行，同时在搜索和展示内容区域之间，增加分隔符

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#2]
美化搜索区域：针对资源管理界面：
1. 搜索部分分成两行，同时在搜索和展示内容区域之间，增加分隔符。
2. 在图片展示部分，增加fieldset效果
3. 图片缩略图展示的时候，文字部分只需要description（不需要title），并且文字部分作为半透明的一个dev，覆盖在图片底部。如果这个不好实现，按照Jacky说的，直接去掉description。

**Comment by JackyReal** [comment]
面板右边的button 统一为 ： 新增，修改，删除

**Comment by microlcl** [comment]
De Quan, 
bootstrap的well样式可以达到inset的效果，我简单修改了一下这个页面的图片区域，增加了well样式，同时去掉了图片下面的title。抛砖引玉，仅供参考：
https://github.com/microlcl/scheme_repo/commit/07eb539334e2d12d549552778f7ba134cc6699cb

另外，我看到有很多针对bootstrap的scheme：
https://wrapbootstrap.com/
期待大家都对我们的界面方案有更多的output。

**Comment by DevinYDQ** [comment]
"文字部分作为半透明的一个dev，覆盖在图片底部" 意思是说 文字以半透明的形式显示在图片底部，而不是向现在另起一行？

**Comment by DevinYDQ** [comment]
“在图片展示部分，增加fieldset效果”   这个还需要做吗？  你说的就是现在well样式的效果吧？

**Comment by microlcl** [comment]
"文字部分作为半透明的一个dev，覆盖在图片底部" 意思是说 文字以半透明的形式显示在图片底部，而不是向现在另起一行？
---------是的，DeQuan

“在图片展示部分，增加fieldset效果” 这个还需要做吗？ 你说的就是现在well样式的效果吧？
---------well样式效果很一般，这个task的目的是让你美化一下这个页面。相信你有更好的办法美化他。
