### ISSUE TITLE
产品修改与增加页面：如果增加了相同的category及其图片，后台报异常

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#20]
增加类别的时候，
1.增加一个类别，及其图片
2.在增加一个类别，此类别和1中的类别一模一样（category一样，图片一样）
3. 提交。
4. 500异常。

这个需要前台校验充分，禁止增加一模一样的类别。

**Comment by 118yangbin** [comment]
前台已经增加验证，如果分类有重复，不允许提交。
