### ISSUE TITLE
实现问题管理模块

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#30]
问题管理模块的增删改查，
只涉及一个table:
questions

**Comment by microlcl** [comment]
修改逻辑：
1. 按照paper_answer 表校验， 如果此问题已经有答案了，选项右侧的删除按钮禁用，同时在表单顶部给个警告信息，告诉用户，此问题正在使用，不能删除选项
2. 如果paper_answer表里面没有答案，但是在paper_question里面有记录，者在表单顶部给提示：警告用户需谨慎修改，同时把引用它的paper用link的形式列出来，用户点击link，可以跳转到paper的详细页面

**Comment by JackyReal** [comment]
for 2,也许提示出来那些问卷使用了这些问题够用了，不需要提供link 什么的，如果effort 比较多

**Comment by DevinYDQ** [comment]
如果正在使用，是否可以修改呢？

**Comment by microlcl** [comment]
删除整个问题的校验逻辑：
1. 如果此问题在paper_question table里面有记录，删除的时候给一个警告提示。
2. 所有的删除都是逻辑删除，也就是把trashed字段设置为T。
