### ISSUE TITLE
客户到访：到访记录查询

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#36]
1. 涉及table: visit_activities, cases
2. 使用者为前台人员，所以visit_type固定为“到访”（visit_type在category table 配置）
3. 显示字段：
   visit_id，visit_stime，business_type，is_visited，case_title
   其中case_title从cases table得到。
4. 查询字段：
   visit_stime，business_type，is_visited
5. 在显著位置增加两个button: "第一次到访"，“非第一次到访”
   5.1: 点击“第一次到访”， 跳转到“增加到访记录”页面
   5.2 点击“非第一次到访”， 跳转到cases的查询列表页面。

**Comment by lss0720** [comment]
已实现。
