### ISSUE TITLE
case查询列表：完成case的查询列表功能

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#37]
1. 涉及table:cases, spaces
2. 显示字段：
   case_id,
   case_title,
        assigned_department_id,
   case_owner,
   business_type varchar(64),
   event_time timestamp, 
   guess_num int, 
   space_name,
   status varchar(64), 
3. 查询字段：
   提供按部门， case_owner, business_type,  event_time， keywords等的查询
4. 请仔细check cases table的schema，里面针对每个字段有详细注释

**Comment by DevinYDQ** [comment]
business_code varchar(6),-- 默认为C, 与case_id 联合组成business_id,与paper_answers table相关联  
C代表什么？

**Comment by DevinYDQ** [comment]
Case类也应该创建一个created_time变量吧？

**Comment by JackyReal** [comment]
business_code == C 只是为了避免主键冲突而设定的；

春雷，
显示id 貌似帮助不大，不过我们后续看一下效果在refactor 列表显示的信息吧
