### ISSUE TITLE
客户到访：增加初次到记录功能

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#38]
完成“增加到访记录”的功能：
1. 涉及table:
visit_activities
cases
customers
2. 表单中需要填写的字段：
visit_activities中的字段：
visit_type varchar(64), -- 访问类别： 到访，回访，在category table配置
visit_stime timestamp,  -- 默认是系统时间，可以修改
visitor_num int,    -- 到访，回访人数
business_type varchar(64), -- 庆典种类：婚庆，生日，公司年会等，可以在category table配置
is_visited varchar(1), -- 是否初次到访： Ture/False
comment varchar(256), -- 备注

cases中的字段：
business_type varchar(64),   -- 庆典种类：婚庆，生日，公司年会等（由于这个字段在visit_activities也有，所以界面上只提供一个地方输入，后台写库的时候分别写入两个tables中）
event_time timestamp,    -- 庆典时间
guess_num int,     -- 客人人数
space_tip varchar(64), -- 庆典地点信息，由前台文字输入。后续跟单者可以根据这个信息完成space_id字段的填写。
1. 后台写库算法：
   3.1 增加一个空记录到customers table中，
   3.2 增加一条记录到cases table中
   3.2 增加一条记录到visit_activities，3.1中增加的customer_id， 3.2中增加的case_id,需要一并写入visit_activities中

**Comment by lss0720** [comment]
功能已实现。
