### ISSUE TITLE
spaces 选择器： 采用popup模态框选择space

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#39]
1. 此spaces选择器需要在case的编辑页面用到。
2. space可以折叠展开，展开后是详细信息。
3. 请参照现有的问题选择框实现。

**Comment by DevinYDQ** [comment]
详细信息除了显示space信息，相关联的场地信息，场地特殊等信息也要显示出来吗？  或者说要把场地管理查看功能里的会场信息都显示出来吗？

**Comment by microlcl** [comment]
关于2：
展开后显示的是space的详细信息, 包括holder相关信息。
类似于：
http://localhost:8080/myprogram/holder/show/holderInfo/12
不过可以做的相对简洁些，可以增加一个类似"More"的link，点击后跳转的场地管理模块的对应页面，以便用户查看更详细的信息。
