### ISSUE TITLE
customer增加页面：model popup window

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#42]
此popupwindo需要在case模块中使用，需要的效果如下：
1. 用此popup window可以新增一个customer, customers table里面的字段都要涵盖到
2. 第一个字段应该是电话号码输入框：
2.1 输入一个电话号码，并失去焦点，此时触发失去焦点事件，进而放送一个ajax请求道后台查询数据库， 看看customers table里面有没有这个电话号码。
2.2. 如果这个电话号码已经存在在DB中，返回此人的所有信息，自动填写此popup的其他字段，并可继续修改。
2.2. 如果没有，允许用户继续输入。
3 点击确定按钮后，写库，并返回包括customer_id在内的所有字段组成的json对象给callback 函数使用。

**Comment by JackyReal** [comment]
春雷，这个地方是进店模块用到的吧？

**Comment by microlcl** [comment]
Jacky, 前台不用这个。
这个是需求管理的case模块用到的，需要填写到访者，新娘，新郎等的时候用到。

**Comment by JackyReal** [comment]
但是像主角这样的客户信息是会默认铺在表单上的，这样会更方便一些？

**Comment by microlcl** [comment]
Jacky：是的，根据我们的讨论，表单上会根据不同的策划类型显示相应的主角输入字段，但是输入的具体内容是通过这个弹出框输入的，因为customer的信息包含的字段比较多，这样似乎比较合理一点
在 2014-1-11 下午10:25，"JackyReal" notifications@github.com写道：
