### ISSUE TITLE
在digitalocean的VPS上安装svn server，并为每个人增加account

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#45]
在digitalocean的VPS上安装svn server，并为每个人增加account

**Comment by microlcl** [comment]
svn server的安装是最高优先级的。
接下来可以：
1. mysql server的安装
2. tomcat的安装
3. bugzillar的安装（也许我们需要这个bug/US跟踪管理系统）

**Comment by lss0720** [comment]
svn server已经ready，接下来装mysql server
