### ISSUE TITLE
产品管理：修改产品详细页面

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#51]
目前的详细页面是：
http://localhost:8080/myprogram/product/view?productId=3
由于现在的产品列表页面展示的是product + categoryid定位的具体产品，所以，点击产品的图片后，需要跳转的详细页面，也应相应调整：
url应该调整为：
http://localhost:8080/myprogram/product/view?productId=3&categoryid=123
即增加一个categoryid的传入参数
页面也需要化繁为简，只需要展示productid+categoryid确定的那个图片， 不需要现在的那个展示多个图片的效果。
文字展示部分保留。

**Comment by microlcl** [comment]
YangBin,这个task开始没？

**Comment by 118yangbin** [comment]
已经开始了，正在做这个。

**Comment by 118yangbin** [comment]
已经修改了产品list页面的价格、分类、图片信息，原来设计是用默认的图片，价格没有关联分类。
产品详细页面，用了product + categoryid定位的单个具体产品。

**Comment by microlcl** [comment]
产品详细页面还是没有调整：
页面也需要化繁为简，只需要展示productid+categoryid确定的那个图片， 不需要现在的那个展示多个图片的效果。
文字展示部分保留。
