### ISSUE TITLE
方案管理：实现“下载历史”tab 页面功能

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#54]
加一个“下载历史”tab 页面，里面显示所有的资源下载历史。 当用户下载图片或者产品，或者音频的时候，下载完毕跳转到这个tab 页面。
需要展示出此人对于这个case的所有方案资源的下载列表。
表结构随后ready。

**Comment by microlcl** [comment]
分成两个table： 一个记录resource的下载，一个记录product的下载：
create table download_resource_history (
    download_resource_id bigint generated by default as identity,
    user_id varchar(64) not null,    -- 下载人
    case_id bigint not null,  
    scheme_id bigint not null,
    media_id bigint not null, -- 图片id
    media_type varchar(10),    -- 音频，视频，图片
    download_datetime timestamp not null,  -- 下载发生的时间
    primary key (download_resource_id)  
);

create table download_product_history (
    download_product_id bigint generated by default as identity,
    user_id varchar(64) not null,    -- 下载人
    case_id bigint not null,  
    scheme_id bigint not null,
    product_id bigint not null, 
    category_id varchar(64) not null, --product 分类id
    download_datetime timestamp not null,  -- 下载发生的时间
    primary key (download_product_id)  
);

**Comment by DevinYDQ** [comment]
我有点疑问，下载记录不应是用户对这个scheme的资源下载记录吗？
