### ISSUE TITLE
进店管理：初次到访页面校验有问题

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#57]
1. 页面校验有问题
2. 案例名称不显示，自动产生： 案例时间-策划类别-场地
   如果场地缺少，就是： 
   案例时间-策划类别-场地未选

**Comment by lss0720** [comment]
customer那块儿没有能够实现校验。按照name来校验 customer.\* 会存在js语法错误。

**Comment by lss0720** [comment]
校验已经全部加上。
