### ISSUE TITLE
问题管理：校验也有一个小问题

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#58]
From Jacky：
问题管理模块校验也有一个小问题，开始的时候我们默认 问题类型是 ： 单选
然后我换了问题类型，结果提示”请填写所有选项“
这个问题优先级相对低一些。

**Comment by lss0720** [comment]
我怎么觉得这个不是bug呢？如果是单选和多选、必须至少有两个答案啊？如果你的答案都为空、那么肯定会提示“请填完所有选项”啊？这不是正常的吗？如果是开放性问题、那么就不会提示“请填完所有选项”了。

**Comment by JackyReal** [comment]
我刚测试了一下，这个问题不存在了。
之前是这样的， 我一换问题类型，即使是开放性问题，也有那个提示
