### ISSUE TITLE
产品详细信息展示功能

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#6]
按照12月6号晚上的meeting讨论结果， 需要参照淘宝的商品展示页面，完成产品详细信息的页面展示：
1. 在产品list页面页面，点击缩略图，直接跳转到产品详细信息页面。
2. 参照淘宝的商品展示页面，完成产品详细信息的页面展示功能。

**Comment by JackyReal** [comment]
右边面板里面的 查看产品  可以去掉；
同时，右边面板里的button 统一为 ： 新增，修改，删除
