### ISSUE TITLE
方案管理：基于模板新建方案

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#60]
在方案编辑页面上，增加一个“以此为模板增加方案”的button，点击后跳转到一个新页面。
在新页面：输入方案名称，用case选择器选择一个case后，点击“增加新方案”按钮，在后台自动增加一个新方案，同时跳转到增加的这个方案的编辑页面。
这个优先级高。

**Comment by DevinYDQ** [comment]
1. 就是将原来方案里面的资源带入到新的方案里面，案例信息和方案基本信息设为空白让用户来填写？
2. 原来方案里面的删除状态的资源是否也带入过去？
3. 新方案的编辑页面是否还需要一个“以此为模板增加方案”的button？

**Comment by microlcl** [comment]
案例信息和方案信息都可以填写：
1. 案例信息：用case选择器选择后，案例信息就有了
2. 方案基本信息： 仔细阅读comment1， “在新页面：输入方案名称，”，说明方案名称也有了，“状态”肯定是“新建”，创建者肯定是登陆人，方案列表沿用模板的方案类别，修改时间就是当前时间，备注可以留空

**Comment by microlcl** [comment]
因为方案的编辑页面本身就有了“以此为模板增加方案”， 你在后台写库新建的方案，在编辑页面看，自然也就有这个button了。
原来方案里面的删除状态的资源不用带入。

**Comment by DevinYDQ** [comment]
进行中
