### ISSUE TITLE
进店管理：非初次到访联系人填写方式

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#62]
用case选择器选择case后，case的联系人信息应该以一种可选的方式呈现出来。
1. 如果此次到访人在这个联系人列表中，直接点选此人，那么此人的信息就自动添加到当前的“联系人”section里面。
2. 如果到访人不在此联系人列表，则沿用当前的方式，在“联系人”section里面添加，save。

**Comment by lss0720** [comment]
已经实现、效果已经提交。
