### ISSUE TITLE
方案模块 ： 添加图片应该支持多选

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#68]
1. 目前弹出的模态窗口里面只能单选
2. 添加成功是否可以让“图片” tab 页面选中？

**Comment by microlcl** [comment]
1. 已经实现图片选择框的多选，并且在方案模块应用了。

2图片Tab页选中，这个需要传一个标识哪个Tab页的参数，参考bootstrap的tab选中的例子修改，assign 给杨斌

**Comment by 118yangbin** [comment]
2.图片添加成功后，图片tab选中。
