### ISSUE TITLE
方案管理模块 ： 查询存在几个问题

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#74]
1. “种类” 字段查询不好用，而且做的选择，查询完，表单上保留不了选择的值
2. 模糊查询字段（带放大镜图标），输入中文乱码，也不好用

**Comment by 118yangbin** [comment]
1.种类字段查询已经改好，表单上也保存了选择的值。
2.中文乱码，这个是本地的tomcat服务器上需要配置。
在tomcat安装目录的Tomacat/conf/server.xml 增加useBodyEncodingForURI="true"这个属性到这一行：
<Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443" useBodyEncodingForURI="true"/>
然后重新建应用程序服务器，添加project.
