### ISSUE TITLE
在server上安装tomcat

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#78]
在server上安装tomcat

**Comment by lss0720** [comment]
根据春雷要求、开始着手安装tomcat在咱们的linux server上面。

**Comment by lss0720** [comment]
JKD 1.6, Tomcat 6都已经安装好。
http://107.170.194.160:8080/
并且MyCommunity也安装好了： http://107.170.194.160:8080/myCommunity/index.jsp
