### ISSUE TITLE
完成产品增加功能

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#8]
完成“增加产品”功能。
目前YangBin已经完成了60%的功能，剩下的功能请Shi Shuai继续完成。

**Comment by JackyReal** [comment]
1）.用户添加分类的时候，图片需要在弹出的模态框里面选择
2). 分类的checkbox 统一放到最左边
3). 产品有一个默认的图片，同样是在弹出的模态框里面选择,这个图片显示在 description 和价格的左边（整个页面最左上角）

**Comment by lss0720** [comment]
1. 需要为产品增加一个默认图片的功能
2. 点击增加分类的button后，会增加一行，增加的一行的第一列里面，默认不应该有图片，而是空出一个图片的位置，并且有提示，告诉用户点击选择图片
3. 后台写库要成功

**Comment by lss0720** [comment]
基本完成。现在新增分类的默认图片也改成了？号。checkbox放到了左边。可以写库成功。
