### ISSUE TITLE
进店管理：把paper选择器应用到增加回访记录里面

### ISSUE THREAD

**Issue by microlcl** [microlcl/scheme_repo#81]
1： 把调查问卷的那个下拉框去掉，同时在“问卷调查”tab页里面增加一个用paper选择器的输入框
2： paper选好后，里面的问题自动显示到“问卷调查”tab里面， 并能填写答案，提交。、
这个是功能性需求，优先级最高，需要尽快实现

**Comment by lss0720** [comment]
已经实现、而且写库成功。
