### ISSUE TITLE
方案管理 ： 添加图片

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#82]
图片选择模态框，确定按钮看不到

**Comment by DevinYDQ** [comment]
我这边没有发现这个问题

**Comment by JackyReal** [comment]
其他人有没有这个问题呢？ 难道是我浏览器的问题？

**Comment by microlcl** [comment]
这个功能是好的，Jacky要不清空一下浏览器的cache再试一下？
Go ahead to close it now :)
