### ISSUE TITLE
新注册用户 ： 默认权限

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#83]
默认注册完的用户，应该有一个默认的权限是用户管理模块（查看，修改 功能？），目前貌似仅有 “方案管理”模块可以默认使用的样子？

**Comment by microlcl** [comment]
新注册的用户只能看到方案管理，是因为现在方案管理根本没有配置到权限管理里面

用户管理模块按照我的理解，是只有admin级别的人才能有的操作， 如果把它作为默认的权限是否不妥？

**Comment by JackyReal** [comment]
我大概理解有误，本意是用户可以查看修改自己的信息，这个不是在用户管理模块的吧，我再看一下

**Comment by microlcl** [comment]
修改个人信息在右上角的button里面。我把修改个人profile作为默认权限了
