### ISSUE TITLE
产品管理模块 ： 预算分类没有加载成功，为空下拉列表

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#86]
重现步骤：

1.新建角色A， 只赋予产品管理模块 --》列表，新增功能
2. 新建用户a，赋予角色A
3. 用户a 登陆

后台错误：
22:38:54.629 [http-bio-8080-exec-9] INFO  c.eastteam.myprogram.web.AuthFilter - in filter: uri=/product/update
22:38:54.803 [http-bio-8080-exec-9] INFO  c.eastteam.myprogram.web.AuthFilter - in filter: uri=/category/api/getChildren/getProductAttribute
22:38:54.803 [http-bio-8080-exec-9] INFO  c.eastteam.myprogram.web.AuthFilter - 没有授权访问此资源
Sep 13, 2014 10:38:54 PM org.apache.catalina.core.StandardWrapperValve invoke

我感觉这个地方，如果是为了得到下拉列表，就不需要控制权限？

**Comment by microlcl** [comment]
Rest service排除在authFilter的处理URL之外
已经fix了
