### ISSUE TITLE
方案管理模块 ：  预算导出功能

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#90]
我上传了一个参考例子到群里面， 导出信息主要有下面一些 ：

***_传播企业活动预算单  
婚礼日期：2013年12月18日                                                  宴会地点：富丽华酒店多功能厅  
公司名称：韩国奥克拉                   电话：                              酒店联系:  
序号  服务项目    单价  数量  单位  总价  备注
    活动布置  
1   庆典拱门    400.00  1   个 400.00  奥克拉门店开业用
2   庆典条幅    300.00  1   个 300.00  奥克拉门店开业用
3   外廊签名墙 80.00   20.4    平米  1632.00     喷绘签名墙，含平面设计，人工搭建。材质：弱溶（富丽华酒店要求平面设计无气味污染，选用无异味材质），尺寸：6m_3.4m
4   外廊地毯    40.00   20  延长米   800.00  外廊迎宾地毯，幅宽1.5m
小计  3132.00

**Comment by microlcl** [comment]
我看了Jacky上传的xsl文件，
1. 这个是按照“预算分类”进行的分类吧？
2. 要满足这个导出格式，需要修改
2.1 产品管理里面增加“单位”， 表明是“个”，“套”等
2.2 scheme_product这个table需要添加“备注”字段

Jacky：
不知我理解的对否？

**Comment by JackyReal** [comment]
春雷， 单位我感觉需要加一下，那些备注信息等，不需要进DB，导出完，他们还可以修改的。
Case 那些基本信息是需要导出的，还有整个的产品和服务列表，以及根据预算分类的小计等

**Comment by microlcl** [comment]
Jacky，
还有一个问题，是不是应该先在页面上用html的格式把统计信息预览一下，然后在下面加个button"导出"，点击此button，就到处为excel格式的文件了？

**Comment by JackyReal** [comment]
不用预览也可以，因为目前页面上已经有小计合计等了，预览是不是还要一些efforts 的啊
