### ISSUE TITLE
统计功能 ： 进店信息统计

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#94]
我们需要一个统计文件夹 ： 类似现在的 “业务”， “管理”， 下面对应具体的的统计报表

进店信息统计/报表   模块：
可以支持用户输入起始，结束时间区间，然后可以看到该段时间 进店趋势图， 分两条线 ： 新客户（初次到访的）， 老客户（非初次到访）

横向坐标（X） 代表具体的某一天，纵向坐标轴（Y) 代表当天的进店数量。
我们也可以自由想一下还有什么统计信息可以帮助公司决策管理等 。。。

**Comment by microlcl** [comment]
1. 这个统计的数据来源为visit_activities
2. 图表可以用JQuery的图表插件来实现：
   http://www.oschina.net/project/tag/275/jquery-chart

**Comment by lss0720** [comment]
接下来开始实现这个功能模块儿。

**Comment by lss0720** [comment]
春雷、Jacky、到访和回访的统计、按照月份的统计已经实现。
