### ISSUE TITLE
统计功能 ： 资源信息统计

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#96]
统计功能 ： 资源信息统计

目前大致有四个需求点 ：

1）. 按照资源本身的角度
    按照时间区间，统计一下 有哪些资源增加或者更新过
    有哪些资源在这个时间段内从未被更新过？
    在这段时间段内， top 10 被用到的产品

2）. 按照使用者的角度
    按照时间区间，统计一下引用资源按照用户的分布图形。
    X 轴代表用户，Y 轴代表引用资源的数量（主要是下载业务）

表现形式我们可以后续一起细致的考虑一下

**Comment by microlcl** [comment]
Jacky：
1）的“产品”，其实是“资源”吧？

**Comment by JackyReal** [comment]
是的， 我写的有误 -:)

**Comment by microlcl** [comment]
这个类似于 task 95
https://github.com/microlcl/scheme_repo/issues/95
在medias table里面也增加了两个字段：
    create_timestamp timestamp,
    modify_timestamp timestamp,

**Comment by DevinYDQ** [comment]
1和2是不是分别创建一个统计图？ 
1是显示时间段起止日期内的top10资源
2是显示top10被下载过的资源及其次数

**Comment by DevinYDQ** [comment]
1对应三种情况，应该用三个图表吧
