### ISSUE TITLE
问题管理模块 ： 问题增加权限有问题

### ISSUE THREAD

**Issue by JackyReal** [microlcl/scheme_repo#98]
重新步骤 ：
1. 新建角色 A： 包含问题管理模块，增加功能
2. 新建用户 a ： 赋予角色A

用用户a 登陆，问题管理模块看不到“新建问题”按钮

应该是系统基础数据里面那个按钮的function id 不对？

**Comment by microlcl** [comment]
Jacky, 
fixed.
question 配置时候function id不对
